### ISSUE TITLE
'Module' has no attribute 'parse_context'

### ISSUE THREAD

**Issue by StayAWhileAndListen** [spulec/uncurl#23]
I try the example code with the attribute parse_context, but i get the error that tell me that this attribute was not known. Did I miss something ?
<img width="604" alt="Capture d’écran 2019-04-06 à 09 40 50" src="https://user-images.githubusercontent.com/48315204/55666504-1ab1d200-5850-11e9-81f3-f1b470f8818d.png">

**Comment by spulec** [comment]
It looks like this version is in `master`, but hasn't been released yet.

**Comment by spulec** [comment]
This should be fixed with `0.0.10`
