### ISSUE TITLE
Replace xerox by pyperclip

### ISSUE THREAD

**Issue by fhoehle** [spulec/uncurl#34]
@spulec Thanks for this helpful tool! I'm having some trouble with the `xerox` setup and unfortunately its latest release is four years old [see](https://github.com/applecrazy/xerox). Would it be possible to switch to [`pyperclip`](https://pypi.org/project/pyperclip/)?

**Comment by spulec** [comment]
Closed with https://github.com/spulec/uncurl/pull/35
